name: Continuous Integration
on: pull_request

jobs:
  CI:
    name: macOS CI
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
      - name: Install packages
        run: flutter pub get
      - name: Format
        run: dart format lib
      - name: Run dart fix
        run: dart fix --apply
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test --update-goldens
